# Jenkins namespace, deployment, persistent volume and load balancer creation
# Execute kubectl logs jenkins-deployment-xxxx --namespace jenkins to see the password for the first time
---
# NAMESPACE
kind: Namespace
apiVersion: v1
metadata:
  name: jenkins
---
# PERSISTENT VOLUME
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: jenkins
  labels:
    app: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkinsci/blueocean
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-persistent-storage
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-persistent-storage
        - persistentVolumeClaim:
            claimName: jenkins-pv-claim
          name: jenkins-cl
---
# LOAD BALANCER
kind: Service
apiVersion: v1
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 8080
  selector:
    app: jenkins
